### ISSUE TITLE
Fails on PNGs (or other base64 strings that aren't packed)

### ISSUE THREAD

**Issue by baoist** [lebedev-yury/carrierwave-base64#3]
Looks like this happens around: https://github.com/lebedev-yury/carrierwave-base64/blob/master/lib/carrierwave/base64/orm/activerecord.rb#L10
```ruby
data.strip.end_with?("==")
```

**Comment by lebedev-yury** [comment]
Can you please give me an example of data, which you try to submit?

**Comment by hopsor** [comment]
I also experienced this problem and solved it by removing that condition. It turns out not all image's base64 strings end with "==". You can read more about that here:

http://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end

Regarding my [solution](https://github.com/hopsor/carrierwave-base64/commit/593178f91546c78d42789fc9f06ac582a26d442e) I'm not really sure if it's the best one but it works anyways. On the other hand we can add a regular expression to make sure the string is a base64 encoded one but it might not be very efficient since most of the base64 strings are gonna be really long.

**Comment by lebedev-yury** [comment]
If so, then it makes to sense to keep an additional condition in the code. The check for the string type should already do the separation of uploaded files from encoded strings.

Can you do a pull request then?
